apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
        - name: go-api
          image: your-docker-registry/go-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_HOST
              value: $POSTGRES_HOST
            - name: POSTGRES_PORT
              value: $POSTGRES_PORT
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: POSTGRES_USER
              value: $POSTGRES_USER
            - name: POSTGRES_PASSWORD
              value: $POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: $POSTGRES_DB
            - name: JWT_SECRET
              value: $JWT_SECRET
