apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
        - name: go-api
          image: your-docker-registry/go-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: DB_USER
              value: ykarabul
            - name: DB_PASSWORD
              value: yigitsh
            - name: DB_NAME
              value: DMQS
            - name: JWT_SECRET
              value: a1b2c3d4e5f6g7h8i9j0
