apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
spec:
  selector:
    matchLabels:
      app: dmqs-app
  template:
    metadata:
      labels:
        app: dmqs-app
    spec:
      containers:
        - name: dmqs-app
          image: yigithankarabulut/dmqsapp:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
              - name: DB_HOST
                value: your-secret
              - name: DB_PORT
                value: your-secret
              - name: REDIS_HOST
                value: your-secret
              - name: REDIS_PORT
                value: your-secret
              - name: DB_USER
                value: your-secret
              - name: DB_PASS
                value: your-secret
              - name: DB_NAME
                value: your-secret
              - name: JWT_SECRET
                value: your-secret
