apiVersion: v1
kind: Service
metadata:
  name: go-api-service
spec:
  selector:
    app: dmqs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
  type: NodePort