apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres
spec:
  containers:
    - name: postgres-container
      image: dmqs-postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_DB
          value: DMQS
        - name: POSTGRES_USER
          value: ykarabul
        - name: POSTGRES_PASSWORD
          value: yigitsh